### ISSUE TITLE
Firefox's benchmark results differ considerably compared to chrome

### ISSUE THREAD

**Issue by arielschiavoni** [evancz/ui-perf#4]
Hi @evancz amazing work with Elm 👍 I am really looking forward to add some Elm at work.

I found that the benchmark results differ in a considerable way when I tried it in Firefox.

Environment:
- MacBook Pro (Retina, 15-inch, Mid 2014)
- OSX El Capitan 10.11.6

`Firefox 48.0.2`

<img width="1438" alt="performancecomparison_firefox48" src="https://cloud.githubusercontent.com/assets/1364564/18098706/a462ddea-6ee3-11e6-825f-93cc925150db.png">

As you can see in the screenshot `Angular 2` is the winner in both naive and optimized implementation. Also it is quite strange why there such a big performance difference in almost all implementation, they are approx. 2X slower in firefox than in chrome.

`Chrome 52`

<img width="1440" alt="performancecomparison_chrome52" src="https://cloud.githubusercontent.com/assets/1364564/18098705/a461a95c-6ee3-11e6-9566-bf2a3770ef77.png">

**Comment by arielschiavoni** [comment]
My fault, I have just read the README.md and I found the link to the comparison between the different browsers.

https://github.com/evancz/react-angular-ember-elm-performance-comparison/tree/master/graphs

Thanks.

**Comment by evancz** [comment]
Yeah, I noticed that as well. Firefox is crazily slower than the rest, and I'm not sure why.

In the past, it was true that Firefox did not have a generational garbage collector (or did not mark-sweep?) and that made it behave very different than Chrome with immutable stuff. So the Angular 2 vs Elm _may_ be accounted for by differences in GC, but I don't know if the GC situation has changed over there since I last heard up-to-date information!

As to why it is so much slower when you do React-vs-React or Elm-vs-Elm on different browsers, I really have no clear concept. I'd expect that's due to the underlying DOM implementation, but that is just speculation.

If there's something that needs changing, let's open a new issue about that specifically!
